<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPBYMINW2444" name="by.epam.atmentoring.unittest.CalculatorTestSqrt" tests="6" failures="0" timestamp="11 Jun 2017 09:24:13 GMT" time="0.003" errors="1">
  <testcase name="testSqrt" time="0.000" classname="by.epam.atmentoring.unittest.CalculatorTestSqrt"/>
  <testcase name="testSqrt" time="0.001" classname="by.epam.atmentoring.unittest.CalculatorTestSqrt">
    <error type="org.testng.TestException" message="
Method CalculatorTestSqrt.testSqrt(double)[pri:0, instance:by.epam.atmentoring.unittest.CalculatorTestSqrt@46d56d67] should have thrown an exception of type class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method CalculatorTestSqrt.testSqrt(double)[pri:0, instance:by.epam.atmentoring.unittest.CalculatorTestSqrt@46d56d67] should have thrown an exception of type class java.lang.NumberFormatException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testSqrt -->
  <testcase name="testSqrt" time="0.001" classname="by.epam.atmentoring.unittest.CalculatorTestSqrt"/>
  <testcase name="testSqrt" time="0.000" classname="by.epam.atmentoring.unittest.CalculatorTestSqrt"/>
  <testcase name="testSqrt" time="0.000" classname="by.epam.atmentoring.unittest.CalculatorTestSqrt"/>
  <testcase name="testSqrt" time="0.001" classname="by.epam.atmentoring.unittest.CalculatorTestSqrt"/>
</testsuite> <!-- by.epam.atmentoring.unittest.CalculatorTestSqrt -->
